export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";
export const GET_LIST_WATCH_ITEM = "GET_LIST_WATCH_ITEM";
export const GET_PROFILE_DETAIL = "GET_PROFILE_DETAIL";
export const GET_PARTICIPATING_PRODUCT = "GET_PARTICIPATING_PRODUCT";
export const GET_ALL_USER = "GET_ALL_USER";
export const GET_LIST_PRODUCT_PENDING = "GET_LIST_PRODUCT_PENDING";
