export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY";
export const GET_LIST_WATCH_ITEM = "GET_LIST_WATCH_ITEM";
